mod sidebar;
mod installation;
mod home_header;
mod hero;
pub mod home_section;
mod theme_section;
mod home_cta;
mod footer;
mod quick_start;
mod documentation;
mod why_section;
mod prop_table;

pub(crate) use sidebar::*;
pub(crate) use installation::*;
pub(crate) use home_header::*;
pub(crate) use hero::*;
pub(crate) use theme_section::*;
pub(crate) use home_cta::*;
pub(crate) use footer::*;
pub(crate) use quick_start::*;
pub(crate) use documentation::*;
pub(crate) use why_section::*;
pub(crate) use prop_table::*;